### ISSUE TITLE
Bad practice

### ISSUE THREAD

**Issue by efiand** [don-kamaz/aim-game-sources#1]
https://github.com/don-kamaz/aim-game-sources/blob/7343ae13baf7a55707d165ebc9d03813a7957646/styles.css#L4

Надежнее делать немного иначе (потому что на сайты могут потом встраиваться виджеты, у которых предполагается не border-box, а content-box; иногда заказчик может встраивать такие виджеты уже после выпуска проекта, а потом приходить с претензиями, поэтому логично сразу делать хорошо):

```css
html {
  box-sizing: border-box;
}

*,
*::before,
*::after {
  box-sizing: inherit;
}
```
